trying out this travis.yml

diff --git a/travis.yml b/travis.yml
--- a/travis.yml
+++ b/travis.yml
@@ -1,12 +1,51 @@
-sudo: false
+# sudo: false
 
-language: node_js
+# language: node_js
 
-node_js:
-  - 18.12.1
+# node_js:
+#   - 18.12.1
+
+# install:
+#   - npm ci
+
+# build:
+#   - npm build:win --config config.mac.json
+
+# language: node_js
+# node_js:
+#   - "18.12.1"
+
+# os:
+#   - linux
+
+before_install:
+  - |
+    case $TRAVIS_OS_NAME in
+      osx)
+        brew update
+        brew install wine
+        ;;
+      *)
+        echo "Error: Unsupported operating system '$TRAVIS_OS_NAME'"
+        exit 1
+        ;;
+    esac
 
 install:
-  - npm ci
+  - npm install
 
-build:
-  - npm build:win --config config.mac.json
+script:
+  - npm run build:mac --config buildConfigs/config.mac.json
+
+before_cache:
+  - rm -rf $HOME/.cache/electron-builder/wine
+
+cache:
+  directories:
+    - node_modules
+    - $HOME/.cache/electron
+    - $HOME/.cache/electron-builder
+
+branches:
+  only:
+    - master
